(function () {
  const rule = (chancePct, rollExpr, scale = 1, category = "") => ({
    chancePct,
    rollExpr,
    scale,
    category,
  });

  const lairCoinScale = 1000;

  const data = {
    metadata: {
      source: "Rules Cyclopedia (Basic PDF), treasure tables on book page 225",
      generatedAt: "2026-03-06",
    },
    verificationNotes: [
      "Treasure Types A-O and P-V are verified against the PDF table (book page 225).",
      "Carried Part 2: S,T gems are 5% for exactly 1 gem (not 1d2).",
      "Lair Type B magic: '10% 1 sword, miscellaneous weapon, or armor' is interpreted as 1d3 between the three categories.",
      "Lair Type F magic: '30% 1 potion, 1 scroll, +3 any but weapons' is interpreted as 3 Any rolls excluding missile/sword/misc weapon.",
      "Special treasure is transcribed from the Special Treasure Value Table; for entries with '/stick', '/vial', '/bottle', the base result is used per unit.",
      "Spice, rare: total gp is calculated as (4d4) times encumbrance (en).",
      "Carried U/V 'Special: Any 1' is interpreted as 1 roll on the Special Treasure Value Table.",
      "Magic item generation uses the Main Table + subtables (including weapon subtables 7-9, sword intelligence, and weapon modifiers) for concrete results.",
    ],
    verificationChecklist: {
      A: true,
      B: true,
      C: true,
      D: true,
      E: true,
      F: true,
      G: true,
      H: true,
      I: true,
      J: true,
      K: true,
      L: true,
      M: true,
      N: true,
      O: true,
      P: true,
      Q: true,
      R: true,
      S: true,
      T: true,
      U: true,
      V: true,
    },

    coinToGp: { cp: 0.01, sp: 0.1, ep: 0.5, gp: 1, pp: 5 },

    lairTypes: {},
    carriedTypes: {},
    gemValueTable: [],
    jewelryValueTable: [],
    jewelryTypeTable: { common: [], uncommon: [], rare: [] },
    specialTreasureTable: [],
    magic: {},
  };

  data.lairTypes = {
    A: {
      kind: "lair",
      part1: {
        cp: rule(25, "1d6", lairCoinScale, "coin"),
        sp: rule(30, "1d6", lairCoinScale, "coin"),
        ep: rule(20, "1d4", lairCoinScale, "coin"),
        gp: rule(35, "2d6", lairCoinScale, "coin"),
        pp: rule(25, "1d2", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(50, "6d6", 1, "gems"),
        jewelry: rule(50, "6d6", 1, "jewelry"),
        special: rule(10, "1d2", 1, "special"),
        magic: { chancePct: 30, recipe: { anyCount: 3, excludeCategories: [] } },
      },
    },
    B: {
      kind: "lair",
      part1: {
        cp: rule(50, "1d8", lairCoinScale, "coin"),
        sp: rule(25, "1d6", lairCoinScale, "coin"),
        ep: rule(25, "1d4", lairCoinScale, "coin"),
        gp: rule(35, "1d3", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(25, "1d6", 1, "gems"),
        jewelry: rule(25, "1d6", 1, "jewelry"),
        magic: {
          chancePct: 10,
          recipe: {
            fixedPicks: [{ kind: "swordOrMiscWeaponOrArmor", countExpr: "1" }],
            anyCount: 0,
            excludeCategories: [],
          },
        },
      },
    },
    C: {
      kind: "lair",
      part1: {
        cp: rule(20, "1d12", lairCoinScale, "coin"),
        sp: rule(30, "1d4", lairCoinScale, "coin"),
        ep: rule(10, "1d4", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(25, "1d4", 1, "gems"),
        jewelry: rule(25, "1d4", 1, "jewelry"),
        special: rule(5, "1d2", 1, "special"),
        magic: { chancePct: 10, recipe: { anyCount: 2, excludeCategories: [] } },
      },
    },
    D: {
      kind: "lair",
      part1: {
        cp: rule(10, "1d8", lairCoinScale, "coin"),
        sp: rule(15, "2d12", lairCoinScale, "coin"),
        gp: rule(60, "1d6", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(30, "1d8", 1, "gems"),
        jewelry: rule(30, "1d8", 1, "jewelry"),
        special: rule(10, "1d2", 1, "special"),
        magic: {
          chancePct: 15,
          recipe: {
            fixedPicks: [
              { kind: "any", countExpr: "2" },
              { kind: "potion", countExpr: "1" },
            ],
            anyCount: 0,
            excludeCategories: [],
          },
        },
      },
    },
    E: {
      kind: "lair",
      part1: {
        cp: rule(5, "1d10", lairCoinScale, "coin"),
        sp: rule(30, "2d12", lairCoinScale, "coin"),
        ep: rule(25, "1d4", lairCoinScale, "coin"),
        gp: rule(25, "1d8", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(10, "1d10", 1, "gems"),
        jewelry: rule(10, "1d10", 1, "jewelry"),
        special: rule(15, "1d2", 1, "special"),
        magic: {
          chancePct: 25,
          recipe: {
            fixedPicks: [
              { kind: "any", countExpr: "3" },
              { kind: "scroll", countExpr: "1" },
            ],
            anyCount: 0,
            excludeCategories: [],
          },
        },
      },
    },
    F: {
      kind: "lair",
      part1: {
        sp: rule(10, "2d10", lairCoinScale, "coin"),
        ep: rule(20, "1d8", lairCoinScale, "coin"),
        gp: rule(45, "1d12", lairCoinScale, "coin"),
        pp: rule(30, "1d3", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(20, "2d12", 1, "gems"),
        jewelry: rule(10, "1d12", 1, "jewelry"),
        special: rule(20, "1d3", 1, "special"),
        magic: {
          chancePct: 30,
          recipe: {
            fixedPicks: [
              { kind: "potion", countExpr: "1" },
              { kind: "scroll", countExpr: "1" },
            ],
            anyCount: 3,
            excludeCategories: ["missileWeapon", "sword", "miscWeapon"],
          },
        },
      },
    },
    G: {
      kind: "lair",
      part1: {
        gp: rule(50, "1d4", lairCoinScale * 10, "coin"),
        pp: rule(50, "1d6", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(25, "3d6", 1, "gems"),
        jewelry: rule(25, "1d10", 1, "jewelry"),
        special: rule(30, "1d3", 1, "special"),
        magic: {
          chancePct: 35,
          recipe: {
            fixedPicks: [
              { kind: "any", countExpr: "4" },
              { kind: "scroll", countExpr: "1" },
            ],
            anyCount: 0,
            excludeCategories: [],
          },
        },
      },
    },
    H: {
      kind: "lair",
      part1: {
        cp: rule(25, "3d8", lairCoinScale, "coin"),
        sp: rule(50, "1d100", lairCoinScale, "coin"),
        ep: rule(50, "1d4", lairCoinScale * 10, "coin"),
        gp: rule(50, "1d6", lairCoinScale * 10, "coin"),
        pp: rule(25, "5d4", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(50, "1d100", 1, "gems"),
        jewelry: rule(50, "1d4", 10, "jewelry"),
        special: rule(10, "1d2", 1, "special"),
        magic: {
          chancePct: 15,
          recipe: {
            fixedPicks: [
              { kind: "potion", countExpr: "1" },
              { kind: "scroll", countExpr: "1" },
              { kind: "any", countExpr: "4" },
            ],
            anyCount: 0,
            excludeCategories: [],
          },
        },
      },
    },
    I: {
      kind: "lair",
      part1: { pp: rule(30, "1d8", lairCoinScale, "coin") },
      part2: {
        gems: rule(50, "2d6", 1, "gems"),
        jewelry: rule(50, "2d6", 1, "jewelry"),
        special: rule(5, "1d2", 1, "special"),
        magic: { chancePct: 15, recipe: { anyCount: 1, excludeCategories: [] } },
      },
    },
    J: {
      kind: "lair",
      part1: {
        cp: rule(25, "1d4", lairCoinScale, "coin"),
        sp: rule(10, "1d3", lairCoinScale, "coin"),
      },
      part2: {},
    },
    K: {
      kind: "lair",
      part1: {
        sp: rule(30, "1d6", lairCoinScale, "coin"),
        ep: rule(10, "1d2", lairCoinScale, "coin"),
      },
      part2: {},
    },
    L: { kind: "lair", part1: {}, part2: { gems: rule(50, "1d4", 1, "gems") } },
    M: {
      kind: "lair",
      part1: {
        gp: rule(40, "2d4", lairCoinScale, "coin"),
        pp: rule(50, "3d10", lairCoinScale, "coin"),
      },
      part2: {
        gems: rule(55, "5d4", 1, "gems"),
        jewelry: rule(45, "2d6", 1, "jewelry"),
      },
    },
    N: {
      kind: "lair",
      part1: {},
      part2: {
        special: rule(10, "1d2", 1, "special"),
        magic: {
          chancePct: 40,
          recipe: { fixedPicks: [{ kind: "potion", countExpr: "2d4" }], anyCount: 0, excludeCategories: [] },
        },
      },
    },
    O: {
      kind: "lair",
      part1: {},
      part2: {
        special: rule(10, "1d3", 1, "special"),
        magic: {
          chancePct: 50,
          recipe: { fixedPicks: [{ kind: "scroll", countExpr: "1d4" }], anyCount: 0, excludeCategories: [] },
        },
      },
    },
  };

  data.carriedTypes = {
    P: { kind: "carried", part1: { cp: rule(null, "3d8", 1, "coin") }, part2: {} },
    Q: { kind: "carried", part1: { sp: rule(null, "3d6", 1, "coin") }, part2: {} },
    R: { kind: "carried", part1: { ep: rule(null, "2d6", 1, "coin") }, part2: {} },
    S: { kind: "carried", part1: { gp: rule(null, "2d4", 1, "coin") }, part2: { gems: rule(5, "1", 1, "gems") } },
    T: { kind: "carried", part1: { pp: rule(null, "1d6", 1, "coin") }, part2: { gems: rule(5, "1", 1, "gems") } },
    U: {
      kind: "carried",
      part1: {
        cp: rule(10, "1d100", 1, "coin"),
        sp: rule(10, "1d100", 1, "coin"),
        gp: rule(5, "1d100", 1, "coin"),
      },
      part2: {
        gems: rule(5, "1d2", 1, "gems"),
        jewelry: rule(5, "1d4", 1, "jewelry"),
        special: rule(2, "1", 1, "special"),
        magic: { chancePct: 2, recipe: { anyCount: 1, excludeCategories: [] } },
      },
    },
    V: {
      kind: "carried",
      part1: {
        sp: rule(10, "1d100", 1, "coin"),
        ep: rule(5, "1d100", 1, "coin"),
        gp: rule(10, "1d100", 1, "coin"),
        pp: rule(5, "1d100", 1, "coin"),
      },
      part2: {
        gems: rule(10, "1d2", 1, "gems"),
        jewelry: rule(10, "1d4", 1, "jewelry"),
        special: rule(5, "1", 1, "special"),
        magic: { chancePct: 5, recipe: { anyCount: 1, excludeCategories: [] } },
      },
    },
  };

  data.gemValueTable = [
    { min: 1, max: 3, valueGp: 10, types: ["Agate", "Quartz", "Turquoise"] },
    { min: 4, max: 10, valueGp: 50, types: ["Crystal", "Jasper", "Onyx"] },
    { min: 11, max: 25, valueGp: 100, types: ["Amber", "Amethyst", "Coral", "Garnet", "Jade"] },
    { min: 26, max: 46, valueGp: 500, types: ["Aquamarine", "Pearl", "Topaz"] },
    { min: 47, max: 71, valueGp: 1000, types: ["Carbuncle", "Opal"] },
    { min: 72, max: 90, valueGp: 5000, types: ["Emerald", "Ruby", "Sapphire"] },
    { min: 91, max: 97, valueGp: 10000, types: ["Diamond", "Jacinth"] },
    { min: 98, max: 100, special: true, types: ["Starstone", "Tristal"] },
  ];

  data.jewelryValueTable = [
    { min: 1, max: 1, valueGp: 100, enc: 10 },
    { min: 2, max: 3, valueGp: 500, enc: 10 },
    { min: 4, max: 6, valueGp: 1000, enc: 10 },
    { min: 7, max: 10, valueGp: 1500, enc: 10 },
    { min: 11, max: 16, valueGp: 2000, enc: 10 },
    { min: 17, max: 24, valueGp: 2500, enc: 10 },
    { min: 25, max: 34, valueGp: 3000, enc: 25 },
    { min: 35, max: 45, valueGp: 4000, enc: 25 },
    { min: 46, max: 58, valueGp: 5000, enc: 25 },
    { min: 59, max: 69, valueGp: 7500, enc: 25 },
    { min: 70, max: 78, valueGp: 10000, enc: 25 },
    { min: 79, max: 85, valueGp: 15000, enc: 25 },
    { min: 86, max: 90, valueGp: 20000, enc: 50 },
    { min: 91, max: 94, valueGp: 25000, enc: 50 },
    { min: 95, max: 97, valueGp: 30000, enc: 50 },
    { min: 98, max: 99, valueGp: 40000, enc: 50 },
    { min: 100, max: 100, valueGp: 50000, enc: 50 },
  ];

  data.jewelryTypeTable = {
    common: ["Anklet", "Beads", "Bracelet", "Brooch", "Buckle", "Cameo", "Chain", "Clasp", "Locket", "Pin"],
    uncommon: [
      "Armband",
      "Belt",
      "Collar",
      "Earring",
      "Four-Leaf Clover",
      "Heart",
      "Leaf",
      "Necklace",
      "Pendant",
      "Rabbit's Foot",
    ],
    rare: ["Amulet", "Crown", "Diadem", "Medallion", "Orb", "Ring (nonmagical)", "Scarab", "Scepter", "Talisman", "Tiara"],
  };

  data.specialTreasureTable = [
    { min: 1, max: 10, item: "Book, rare", encExpr: "2d100", valueExpr: "1d100", valueScale: 10 },
    { min: 11, max: 12, item: "Fur, common (pelt)", encExpr: "1d6", encScale: 10, valueExpr: "1d4" },
    { min: 13, max: 17, item: "Fur, common (cape)", encExpr: "1d8+4", encScale: 10, valueExpr: "1d6", valueScale: 100 },
    { min: 18, max: 20, item: "Fur, common (coat)", encExpr: "2d6+8", encScale: 10, valueExpr: "3d4", valueScale: 100 },
    { min: 21, max: 22, item: "Fur, rare (pelt)", encExpr: "1d6", encScale: 10, valueExpr: "2d6" },
    { min: 23, max: 27, item: "Fur, rare (cape)", encExpr: "1d8+4", encScale: 10, valueExpr: "4d6", valueScale: 100 },
    { min: 28, max: 30, item: "Fur, rare (coat)", encExpr: "2d6+8", encScale: 10, valueExpr: "1d6", valueScale: 1000 },
    { min: 31, max: 35, item: "Incense, rare", encExpr: "1", valueExpr: "5d6", unit: "stick" },
    { min: 36, max: 40, item: "Perfume, rare", encExpr: "1", valueExpr: "1d10+5", valueScale: 10, unit: "vial" },
    { min: 41, max: 55, item: "Rug or tapestry", encExpr: "1d6", encScale: 100, valueExpr: "2d10", unit: "sq yard" },
    { min: 56, max: 65, item: "Silk", encExpr: "1d6", encScale: 10, valueExpr: "1d8" },
    { min: 66, max: 75, item: "Skin, animal", encExpr: "5d4", encScale: 10, valueExpr: "1d10" },
    { min: 76, max: 85, item: "Skin, monster", encExpr: "1d100", encScale: 50, valueExpr: "1d10", valueScale: 100 },
    { min: 86, max: 90, item: "Spice, rare", encExpr: "1d100", valuePerEncExpr: "4d4" },
    { min: 91, max: 95, item: "Statuette", encExpr: "1d100", valueExpr: "1d10", valueScale: 100 },
    { min: 96, max: 100, item: "Wine, rare", encExpr: "1d6+3", encScale: 10, valueExpr: "1d6", unit: "bottle" },
  ];

  data.magic.mainTable = [
    { min: 1, max: 25, category: "potion" },
    { min: 26, max: 37, category: "scroll" },
    { min: 38, max: 46, category: "wandStaffRod" },
    { min: 47, max: 52, category: "ring" },
    { min: 53, max: 62, category: "miscItem" },
    { min: 63, max: 72, category: "armorOrShield" },
    { min: 73, max: 83, category: "missileWeapon" },
    { min: 84, max: 92, category: "sword" },
    { min: 93, max: 100, category: "miscWeapon" },
  ];

  data.magic.potions = [
    { min: 1, max: 2, name: "Agility" },
    { min: 3, max: 3, name: "Animal Control" },
    { min: 4, max: 6, name: "Antidote" },
    { min: 7, max: 8, name: "Blending" },
    { min: 9, max: 10, name: "Bug Repellent" },
    { min: 11, max: 12, name: "Clairaudience" },
    { min: 13, max: 14, name: "Clairvoyance" },
    { min: 15, max: 16, name: "Climbing" },
    { min: 17, max: 18, name: "Defense" },
    { min: 19, max: 22, name: "Delusion" },
    { min: 23, max: 24, name: "Diminution" },
    { min: 25, max: 25, name: "Dragon Control" },
    { min: 26, max: 27, name: "Dreamspeech" },
    { min: 28, max: 28, name: "Elasticity" },
    { min: 29, max: 30, name: "Elemental Form" },
    { min: 31, max: 32, name: "ESP" },
    { min: 33, max: 33, name: "Ethereality" },
    { min: 34, max: 36, name: "Fire Resistance" },
    { min: 37, max: 39, name: "Flying" },
    { min: 40, max: 41, name: "Fortitude" },
    { min: 42, max: 42, name: "Freedom" },
    { min: 43, max: 45, name: "Gaseous Form" },
    { min: 46, max: 46, name: "Giant Control" },
    { min: 47, max: 49, name: "Giant Strength" },
    { min: 50, max: 51, name: "Growth" },
    { min: 52, max: 57, name: "Healing" },
    { min: 58, max: 60, name: "Heroism" },
    { min: 61, max: 61, name: "Human Control" },
    { min: 62, max: 64, name: "Invisibility" },
    { min: 65, max: 66, name: "Invulnerability" },
    { min: 67, max: 68, name: "Levitation" },
    { min: 69, max: 70, name: "Longevity" },
    { min: 71, max: 71, name: "Luck" },
    { min: 72, max: 72, name: "Merging" },
    { min: 73, max: 74, name: "Plant Control" },
    { min: 75, max: 77, name: "Poison" },
    { min: 78, max: 80, name: "Polymorph Self" },
    { min: 81, max: 82, name: "Sight" },
    { min: 83, max: 84, name: "Speech" },
    { min: 85, max: 88, name: "Speed" },
    { min: 89, max: 90, name: "Strength" },
    { min: 91, max: 93, name: "Super-Healing" },
    { min: 94, max: 96, name: "Swimming" },
    { min: 97, max: 97, name: "Treasure Finding" },
    { min: 98, max: 98, name: "Undead Control" },
    { min: 99, max: 100, name: "Water Breathing" },
  ];

  data.magic.scrolls = [
    { min: 1, max: 3, name: "Communication" },
    { min: 4, max: 5, name: "Creation" },
    { min: 6, max: 13, name: "Curse Scroll" },
    { min: 14, max: 14, name: "Delay" },
    { min: 15, max: 17, name: "Equipment" },
    { min: 18, max: 19, name: "Illumination" },
    { min: 20, max: 21, name: "Mages" },
    { min: 22, max: 25, name: "Map to Normal Treasure" },
    { min: 26, max: 28, name: "Map to Magical Treasure" },
    { min: 29, max: 30, name: "Map to Combined Treasure" },
    { min: 31, max: 31, name: "Map to Special Treasure" },
    { min: 32, max: 34, name: "Mapping" },
    { min: 35, max: 36, name: "Portals" },
    { min: 37, max: 42, name: "Protection from Elementals" },
    { min: 43, max: 50, name: "Protection from Lycanthropes" },
    { min: 51, max: 54, name: "Protection from Magic" },
    { min: 55, max: 61, name: "Protection from Undead" },
    { min: 62, max: 63, name: "Questioning" },
    { min: 64, max: 64, name: "Repetition" },
    { min: 65, max: 66, name: "Seeing" },
    { min: 67, max: 68, name: "Shelter" },
    { min: 69, max: 71, name: "Spell Catching" },
    { min: 72, max: 96, name: "Spell Scroll", isSpellScroll: true },
    { min: 97, max: 98, name: "Trapping" },
    { min: 99, max: 100, name: "Truth" },
  ];

  data.magic.spellScrollType = [
    { min: 1, max: 70, type: "Magical" },
    { min: 71, max: 95, type: "Clerical" },
    { min: 96, max: 100, type: "Druidic" },
  ];

  data.magic.spellLevels = {
    clericOrDruid: [
      { min: 1, max: 34, level: 1 },
      { min: 35, max: 58, level: 2 },
      { min: 59, max: 76, level: 3 },
      { min: 77, max: 88, level: 4 },
      { min: 89, max: 95, level: 5 },
      { min: 96, max: 99, level: 6 },
      { min: 100, max: 100, level: 7 },
    ],
    magicUser: [
      { min: 1, max: 28, level: 1 },
      { min: 29, max: 49, level: 2 },
      { min: 50, max: 64, level: 3 },
      { min: 65, max: 75, level: 4 },
      { min: 76, max: 84, level: 5 },
      { min: 85, max: 91, level: 6 },
      { min: 92, max: 96, level: 7 },
      { min: 97, max: 99, level: 8 },
      { min: 100, max: 100, level: 9 },
    ],
  };

  data.magic.wandStaffRod = [
    { min: 1, max: 5, name: "Wand of Cold" },
    { min: 6, max: 10, name: "Wand of Enemy Detection" },
    { min: 11, max: 14, name: "Wand of Fear" },
    { min: 15, max: 19, name: "Wand of Fireballs" },
    { min: 20, max: 23, name: "Wand of Illusion" },
    { min: 24, max: 28, name: "Wand of Lightning Bolts" },
    { min: 29, max: 33, name: "Wand of Magic Detection" },
    { min: 34, max: 38, name: "Wand of Metal Detection" },
    { min: 39, max: 42, name: "Wand of Negation" },
    { min: 43, max: 47, name: "Wand of Paralyzation" },
    { min: 48, max: 52, name: "Wand of Polymorphing" },
    { min: 53, max: 56, name: "Wand of Secret Door Detection" },
    { min: 57, max: 60, name: "Wand of Trap Detection" },
    { min: 61, max: 61, name: "Staff of Commanding" },
    { min: 62, max: 63, name: "Staff of Dispelling" },
    { min: 64, max: 66, name: "Staff of the Druids" },
    { min: 67, max: 69, name: "Staff of an Element" },
    { min: 70, max: 71, name: "Staff of Harming" },
    { min: 72, max: 78, name: "Staff of Healing" },
    { min: 79, max: 79, name: "Staff of Power" },
    { min: 80, max: 82, name: "Snake Staff" },
    { min: 83, max: 85, name: "Staff of Striking" },
    { min: 86, max: 87, name: "Staff of Withering" },
    { min: 88, max: 88, name: "Staff of Wizardry" },
    { min: 89, max: 90, name: "Rod of Cancellation" },
    { min: 91, max: 91, name: "Rod of Dominion" },
    { min: 92, max: 92, name: "Rod of Health" },
    { min: 93, max: 94, name: "Rod of Inertia" },
    { min: 95, max: 95, name: "Rod of Parrying" },
    { min: 96, max: 96, name: "Rod of Victory" },
    { min: 97, max: 99, name: "Rod of Weaponry" },
    { min: 100, max: 100, name: "Rod of the Wyrm" },
  ];

  data.magic.rings = [
    { min: 1, max: 2, name: "Ring of Animal Control" },
    { min: 3, max: 8, name: "Ring of Delusion" },
    { min: 9, max: 9, name: "Ring of Djinni Summoning" },
    { min: 10, max: 13, name: "Ring of Ear" },
    { min: 14, max: 17, name: "Ring of Elemental Adaptation" },
    { min: 18, max: 23, name: "Ring of Fire Resistance" },
    { min: 24, max: 26, name: "Ring of Holiness" },
    { min: 27, max: 27, name: "Ring of Human Control" },
    { min: 28, max: 32, name: "Ring of Invisibility" },
    { min: 33, max: 35, name: "Ring of Life Protection" },
    { min: 36, max: 38, name: "Ring of Memory" },
    { min: 39, max: 40, name: "Ring of Plant Control" },
    { min: 41, max: 45, name: "Ring of Protection +1" },
    { min: 46, max: 48, name: "Ring of Protection +2" },
    { min: 49, max: 50, name: "Ring of Protection +3" },
    { min: 51, max: 51, name: "Ring of Protection +4" },
    { min: 52, max: 55, name: "Ring of Quickness" },
    { min: 56, max: 56, name: "Ring of Regeneration" },
    { min: 57, max: 59, name: "Ring of Remedies" },
    { min: 60, max: 61, name: "Ring of Safety" },
    { min: 62, max: 64, name: "Ring of Seeing" },
    { min: 65, max: 67, name: "Ring of Spell Eating" },
    { min: 68, max: 69, name: "Ring of Spell Storing" },
    { min: 70, max: 71, name: "Ring of Spell Turning" },
    { min: 72, max: 75, name: "Ring of Survival" },
    { min: 76, max: 77, name: "Ring of Telekinesis" },
    { min: 78, max: 81, name: "Ring of Truth" },
    { min: 82, max: 84, name: "Ring of Truthfulness" },
    { min: 85, max: 86, name: "Ring of Truthlessness" },
    { min: 87, max: 91, name: "Ring of Water Walking" },
    { min: 92, max: 96, name: "Ring of Weakness" },
    { min: 97, max: 98, name: "Ring of Wishes" },
    { min: 99, max: 100, name: "Ring of X-ray Vision" },
  ];

  data.magic.miscItems = [
    { min: 1, max: 2, name: "Amulet of Protection from Crystal Balls and ESP" },
    { min: 3, max: 4, name: "Bag of Devouring" },
    { min: 5, max: 9, name: "Bag of Holding" },
    { min: 10, max: 12, name: "Boat, Undersea" },
    { min: 13, max: 14, name: "Boots of Levitation" },
    { min: 15, max: 17, name: "Boots of Speed" },
    { min: 18, max: 19, name: "Boots of Traveling/Leaping" },
    { min: 20, max: 20, name: "Bowl of Commanding Water Elementals" },
    { min: 21, max: 21, name: "Brazier of Commanding Fire Elementals" },
    { min: 22, max: 23, name: "Broom of Flying" },
    { min: 24, max: 24, name: "Censer of Controlling Air Elementals" },
    { min: 25, max: 27, name: "Chime of Time" },
    { min: 28, max: 29, name: "Crystal Ball" },
    { min: 30, max: 30, name: "Crystal Ball with Clairaudience" },
    { min: 31, max: 31, name: "Crystal Ball with ESP" },
    { min: 32, max: 33, name: "Displacer Cloak" },
    { min: 34, max: 34, name: "Drums of Panic" },
    { min: 35, max: 35, name: "Efreeti Bottle" },
    { min: 36, max: 38, name: "Egg of Wonder" },
    { min: 39, max: 40, name: "Elven Boots" },
    { min: 41, max: 42, name: "Elven Cloak" },
    { min: 43, max: 43, name: "Flying Carpet" },
    { min: 44, max: 45, name: "Gauntlets of Ogre Power" },
    { min: 46, max: 47, name: "Girdle of Giant Strength" },
    { min: 48, max: 49, name: "Helm of Alignment Changing" },
    { min: 50, max: 51, name: "Helm of Reading" },
    { min: 52, max: 52, name: "Helm of Telepathy" },
    { min: 53, max: 53, name: "Helm of Teleportation" },
    { min: 54, max: 54, name: "Horn of Blasting" },
    { min: 55, max: 56, name: "Lamp, Hurricane" },
    { min: 57, max: 59, name: "Lamp of Long Burning" },
    { min: 60, max: 61, name: "Medallion of ESP (30' range)" },
    { min: 62, max: 62, name: "Medallion of ESP (90' range)" },
    { min: 63, max: 63, name: "Mirror of Life Trapping" },
    { min: 64, max: 66, name: "Muzzle of Training" },
    { min: 67, max: 68, name: "Nail, Finger" },
    { min: 69, max: 71, name: "Nail of Pointing" },
    { min: 72, max: 76, name: "Ointment" },
    { min: 77, max: 79, name: "Pouch of Security" },
    { min: 80, max: 82, name: "Quill of Copying" },
    { min: 83, max: 86, name: "Rope of Climbing" },
    { min: 87, max: 88, name: "Scarab of Protection" },
    { min: 89, max: 91, name: "Slate of Identification" },
    { min: 92, max: 92, name: "Stone of Controlling Earth Elementals" },
    { min: 93, max: 94, name: "Talisman of Elemental Travel" },
    { min: 95, max: 97, name: "Wheel of Floating" },
    { min: 98, max: 98, name: "Wheel of Fortune" },
    { min: 99, max: 100, name: "Wheel, Square" },
  ];

  data.magic.missileWeaponSubtable = [
    { min: 1, max: 37, item: "Arrows", weaponClass: "A" },
    { min: 38, max: 59, item: "Quarrels", weaponClass: "A" },
    { min: 60, max: 70, item: "Sling stones", weaponClass: "A" },
    { min: 71, max: 72, item: "Blowgun", weaponClass: "D" },
    { min: 73, max: 80, item: "Bow, long", weaponClass: "D" },
    { min: 81, max: 85, item: "Bow, short", weaponClass: "D" },
    { min: 86, max: 87, item: "Crossbow, heavy", weaponClass: "D" },
    { min: 88, max: 92, item: "Crossbow, light", weaponClass: "D" },
    { min: 93, max: 100, item: "Sling", weaponClass: "D" },
  ];

  data.magic.weaponBonusTables = {
    A: [
      { min: 1, max: 40, bonus: 1 },
      { min: 41, max: 67, bonus: 2 },
      { min: 68, max: 84, bonus: 3 },
      { min: 85, max: 94, bonus: 4 },
      { min: 95, max: 100, bonus: 5 },
    ],
    B: [
      { min: 1, max: 50, bonus: 1 },
      { min: 51, max: 74, bonus: 2 },
      { min: 75, max: 88, bonus: 3 },
      { min: 89, max: 96, bonus: 4 },
      { min: 97, max: 100, bonus: 5 },
    ],
    C: [
      { min: 1, max: 60, bonus: 1 },
      { min: 61, max: 81, bonus: 2 },
      { min: 82, max: 92, bonus: 3 },
      { min: 93, max: 98, bonus: 4 },
      { min: 99, max: 100, bonus: 5 },
    ],
    D: [
      { min: 1, max: 70, bonus: 1 },
      { min: 71, max: 88, bonus: 2 },
      { min: 89, max: 96, bonus: 3 },
      { min: 97, max: 99, bonus: 4 },
      { min: 100, max: 100, bonus: 5 },
    ],
  };

  data.magic.additionalWeaponModifiers = {
    sword: [
      { min: 1, max: 29, extra: 1 },
      { min: 30, max: 50, extra: 2 },
      { min: 51, max: 64, extra: 3 },
      { min: 65, max: 72, extra: 4 },
      { min: 73, max: 75, extra: 5 },
      { min: 76, max: 100, talent: true },
    ],
    misc: [
      { min: 1, max: 33, extra: 1 },
      { min: 34, max: 57, extra: 2 },
      { min: 58, max: 73, extra: 3 },
      { min: 74, max: 82, extra: 4 },
      { min: 83, max: 85, extra: 5 },
      { min: 86, max: 100, talent: true },
    ],
  };

  data.magic.weaponOpponents = [
    { min: 1, max: 6, name: "Bugs" },
    { min: 7, max: 9, name: "Constructs" },
    { min: 10, max: 15, name: "Dragonkind" },
    { min: 16, max: 24, name: "Enchanted monsters" },
    { min: 25, max: 36, name: "Giantkind" },
    { min: 37, max: 48, name: "Lycanthropes" },
    { min: 49, max: 52, name: "Planar monsters" },
    { min: 53, max: 58, name: "Regenerating monsters" },
    { min: 59, max: 67, name: "Reptiles and dinosaurs" },
    { min: 68, max: 70, name: "Spell-immune monsters" },
    { min: 71, max: 76, name: "Spellcasters" },
    { min: 77, max: 88, name: "Undead" },
    { min: 89, max: 94, name: "Water-breathing monsters" },
    { min: 95, max: 100, name: "Weapon-using monsters" },
  ];

  data.magic.weaponTalents = [
    { min: 1, max: 5, name: "Breathing" },
    { min: 6, max: 12, name: "Charming" },
    { min: 13, max: 16, name: "Deceiving" },
    { min: 17, max: 23, name: "Defending" },
    { min: 24, max: 25, name: "Deflecting" },
    { min: 26, max: 27, name: "Draining" },
    { min: 28, max: 32, name: "Extinguishing" },
    { min: 33, max: 38, name: "Finding" },
    { min: 39, max: 43, name: "Flaming" },
    { min: 44, max: 46, name: "Flying" },
    { min: 47, max: 54, name: "Healing" },
    { min: 55, max: 59, name: "Hiding" },
    { min: 60, max: 65, name: "Holding" },
    { min: 66, max: 73, name: "Lighting" },
    { min: 74, max: 79, name: "Silencing" },
    { min: 80, max: 81, name: "Slicing" },
    { min: 82, max: 85, name: "Slowing" },
    { min: 86, max: 89, name: "Speeding" },
    { min: 90, max: 94, name: "Translating" },
    { min: 95, max: 99, name: "Watching" },
    { min: 100, max: 100, name: "Wishing" },
  ];

  data.magic.missileTalents = [
    { min: 1, max: 4, name: "Biting" },
    { min: 5, max: 9, name: "Blinking" },
    { min: 10, max: 14, name: "Charming" },
    { min: 15, max: 21, name: "Climbing" },
    { min: 22, max: 31, name: "Curing" },
    { min: 32, max: 34, name: "Disarming" },
    { min: 35, max: 38, name: "Dispelling" },
    { min: 39, max: 45, name: "Flying" },
    { min: 46, max: 52, name: "Lighting" },
    { min: 53, max: 57, name: "Penetrating" },
    { min: 58, max: 61, name: "Refilling" },
    { min: 62, max: 67, name: "Screaming" },
    { min: 68, max: 72, name: "Seeking" },
    { min: 73, max: 76, name: "Sinking" },
    { min: 77, max: 78, name: "Slaying" },
    { min: 79, max: 85, name: "Speaking" },
    { min: 86, max: 89, name: "Stunning" },
    { min: 90, max: 91, name: "Teleporting" },
    { min: 92, max: 96, name: "Transporting" },
    { min: 97, max: 100, name: "Wounding" },
  ];

  data.magic.swordSubtable = [
    { min: 1, max: 65, type: "Sword, normal", weaponClass: "C" },
    { min: 66, max: 84, type: "Sword, short", weaponClass: "C" },
    { min: 85, max: 92, type: "Sword, two-handed", weaponClass: "D" },
    { min: 93, max: 100, type: "Sword, bastard", weaponClass: "D" },
  ];

  data.magic.swordIntelligence = [
    { min: 1, max: 79, int: null, communication: "Nil", languages: "Nil", primaryCount: 0, readsMagic: false, extraordinaryCount: 0 },
    { min: 80, max: 85, int: 7, communication: "Empathy", languages: "Nil", primaryCount: 1, readsMagic: false, extraordinaryCount: 0 },
    { min: 86, max: 90, int: 8, communication: "Empathy", languages: "Nil", primaryCount: 2, readsMagic: false, extraordinaryCount: 0 },
    { min: 91, max: 94, int: 9, communication: "Empathy", languages: "Nil", primaryCount: 3, readsMagic: false, extraordinaryCount: 0 },
    { min: 95, max: 97, int: 10, communication: "Speech", languages: "1d3", primaryCount: 3, readsMagic: false, extraordinaryCount: 0 },
    { min: 98, max: 99, int: 11, communication: "Speech", languages: "1d6", primaryCount: 3, readsMagic: true, extraordinaryCount: 0 },
    { min: 100, max: 100, int: 12, communication: "Speech", languages: "2d4", primaryCount: 3, readsMagic: true, extraordinaryCount: 1 },
  ];

  data.magic.swordPrimaryPowers = [
    { min: 1, max: 10, name: "Detect evil (good)" },
    { min: 11, max: 15, name: "Detect gems" },
    { min: 16, max: 25, name: "Detect magic" },
    { min: 26, max: 35, name: "Detect metal" },
    { min: 36, max: 50, name: "Detect shifting walls and rooms" },
    { min: 51, max: 65, name: "Detect sloping passages" },
    { min: 66, max: 75, name: "Find secret doors" },
    { min: 76, max: 85, name: "Find traps" },
    { min: 86, max: 95, name: "See invisible" },
    { min: 96, max: 99, name: "Roll for 1 extraordinary power", extraordinaryRolls: 1 },
    { min: 100, max: 100, name: "Roll 2 times more this column", extraPrimaryRolls: 2 },
  ];

  data.magic.swordExtraordinaryPowers = [
    { min: 1, max: 10, name: "Clairaudience" },
    { min: 11, max: 20, name: "Clairvoyance" },
    { min: 21, max: 30, name: "ESP" },
    { min: 31, max: 35, name: "Extra damage" },
    { min: 36, max: 40, name: "Flying" },
    { min: 41, max: 45, name: "Healing" },
    { min: 46, max: 54, name: "Illusion" },
    { min: 55, max: 59, name: "Levitation" },
    { min: 60, max: 69, name: "Telekinesis" },
    { min: 70, max: 79, name: "Telepathy" },
    { min: 80, max: 88, name: "Teleportation" },
    { min: 89, max: 97, name: "X-ray vision" },
    { min: 98, max: 99, name: "Roll 2 times more this column", extraRolls: 2 },
    { min: 100, max: 100, name: "Roll 3 times more this column", extraRolls: 3 },
  ];

  data.magic.miscWeaponSubtable = [
    { min: 1, max: 9, weapon: "Axe, battle", weaponClass: "C" },
    { min: 10, max: 15, weapon: "Axe, hand", weaponClass: "B" },
    { min: 16, max: 17, weapon: "Axe, hand (returning)", weaponClass: "B" },
    { min: 18, max: 20, weapon: "Blackjack", weaponClass: "C" },
    { min: 21, max: 22, weapon: "Bola", weaponClass: "B" },
    { min: 23, max: 23, weapon: "Bola (returning)", weaponClass: "B" },
    { min: 24, max: 28, weapon: "Club", weaponClass: "C" },
    { min: 29, max: 40, weapon: "Dagger", weaponClass: "B" },
    { min: 41, max: 43, weapon: "Dagger (returning)", weaponClass: "B" },
    { min: 44, max: 53, weapon: "Hammer, war", weaponClass: "C" },
    { min: 54, max: 56, weapon: "Hammer, war (returning)", weaponClass: "C" },
    { min: 57, max: 59, weapon: "Javelin", weaponClass: "B" },
    { min: 60, max: 60, weapon: "Javelin (returning)", weaponClass: "B" },
    { min: 61, max: 64, weapon: "Lance", weaponClass: "D" },
    { min: 65, max: 76, weapon: "Mace", weaponClass: "C" },
    { min: 77, max: 78, weapon: "Net", weaponClass: "B" },
    { min: 79, max: 79, weapon: "Net (returning)", weaponClass: "B" },
    { min: 80, max: 84, weapon: "Polearm", weaponClass: "D" },
    { min: 85, max: 94, weapon: "Spear", weaponClass: "B" },
    { min: 95, max: 97, weapon: "Spear (returning)", weaponClass: "B" },
    { min: 98, max: 100, weapon: "Whip", weaponClass: "C" },
  ];

  data.magic.armor = {
    sizeTable: [
      { min: 1, max: 68, value: "Human" },
      { min: 69, max: 81, value: "Dwarf" },
      { min: 82, max: 91, value: "Elf" },
      { min: 92, max: 98, value: "Halfling" },
      { min: 99, max: 100, value: "Giant" },
    ],
    typeTable: [
      { min: 1, max: 10, value: "Leather armor", group: "light" },
      { min: 11, max: 17, value: "Scale mail", group: "light" },
      { min: 18, max: 30, value: "Chain mail", group: "chain" },
      { min: 31, max: 39, value: "Banded mail", group: "light" },
      { min: 40, max: 50, value: "Plate mail", group: "plate" },
      { min: 51, max: 55, value: "Suit armor", group: "plate" },
      { min: 56, max: 75, value: "Shield", group: "shield" },
      { min: 76, max: 77, value: "Scale & shield", group: "shield" },
      { min: 78, max: 85, value: "Chain & shield", group: "shield" },
      { min: 86, max: 90, value: "Banded & shield", group: "shield" },
      { min: 91, max: 100, value: "Plate & shield", group: "shield" },
    ],
    bonusTables: {
      light: [
        { min: 1, max: 70, bonus: 1, specialChance: 10 },
        { min: 71, max: 88, bonus: 2, specialChance: 15 },
        { min: 89, max: 96, bonus: 3, specialChance: 20 },
        { min: 97, max: 99, bonus: 4, specialChance: 25 },
        { min: 100, max: 100, bonus: 5, specialChance: 30 },
      ],
      chain: [
        { min: 1, max: 60, bonus: 1, specialChance: 10 },
        { min: 61, max: 81, bonus: 2, specialChance: 15 },
        { min: 82, max: 92, bonus: 3, specialChance: 20 },
        { min: 93, max: 98, bonus: 4, specialChance: 25 },
        { min: 99, max: 100, bonus: 5, specialChance: 30 },
      ],
      plate: [
        { min: 1, max: 50, bonus: 1, specialChance: 10 },
        { min: 51, max: 74, bonus: 2, specialChance: 15 },
        { min: 75, max: 88, bonus: 3, specialChance: 20 },
        { min: 89, max: 96, bonus: 4, specialChance: 25 },
        { min: 97, max: 100, bonus: 5, specialChance: 30 },
      ],
      shield: [
        { min: 1, max: 40, bonus: 1, specialChance: 10 },
        { min: 41, max: 67, bonus: 2, specialChance: 15 },
        { min: 68, max: 84, bonus: 3, specialChance: 20 },
        { min: 85, max: 94, bonus: 4, specialChance: 25 },
        { min: 95, max: 100, bonus: 5, specialChance: 30 },
      ],
    },
    specialPowers: [
      { min: 1, max: 7, value: "Absorption" },
      { min: 8, max: 17, value: "Charm" },
      { min: 18, max: 32, value: "Cure wounds" },
      { min: 33, max: 42, value: "Electricity" },
      { min: 43, max: 47, value: "Energy drain" },
      { min: 48, max: 50, value: "Ethereality" },
      { min: 51, max: 60, value: "Fly" },
      { min: 61, max: 66, value: "Gaseous form" },
      { min: 67, max: 75, value: "Haste" },
      { min: 76, max: 85, value: "Invisibility" },
      { min: 86, max: 93, value: "Reflection" },
      { min: 94, max: 100, value: "Remove curse" },
    ],
  };

  data.magic.magicWeaponGeneration = {
    missile: [
      { min: 1, max: 6, label: "Arrows +1 (2d10)" },
      { min: 7, max: 11, label: "Arrows +2 (2d6)" },
      { min: 12, max: 15, label: "Arrows +3 (2d4)" },
      { min: 16, max: 18, label: "Arrow +1 silver" },
      { min: 19, max: 20, label: "Arrow +2 silver" },
      { min: 21, max: 21, label: "Arrow +3 silver" },
      { min: 22, max: 25, label: "Blowgun +1" },
      { min: 26, max: 28, label: "Bola +1" },
      { min: 29, max: 33, label: "Bow, short +1" },
      { min: 34, max: 37, label: "Bow, short +2" },
      { min: 38, max: 40, label: "Bow, short +3" },
      { min: 41, max: 45, label: "Bow, long +1" },
      { min: 46, max: 49, label: "Bow, long +2" },
      { min: 50, max: 52, label: "Bow, long +3" },
      { min: 53, max: 57, label: "Crossbow, light +1" },
      { min: 58, max: 61, label: "Crossbow, light +2" },
      { min: 62, max: 64, label: "Crossbow, light +3" },
      { min: 65, max: 69, label: "Crossbow, heavy +1" },
      { min: 70, max: 73, label: "Crossbow, heavy +2" },
      { min: 74, max: 76, label: "Crossbow, heavy +3" },
      { min: 77, max: 82, label: "Quarrels +1 (2d10)" },
      { min: 83, max: 87, label: "Quarrels +2 (2d6)" },
      { min: 88, max: 91, label: "Quarrels +3 (2d4)" },
      { min: 92, max: 94, label: "Quarrel +1 silver" },
      { min: 95, max: 96, label: "Quarrel +2 silver" },
      { min: 97, max: 97, label: "Quarrel +3 silver" },
      { min: 98, max: 100, label: "Sling +1" },
    ],
    sword: [
      { min: 1, max: 10, label: "Sword, short +1" },
      { min: 11, max: 20, label: "Sword, short +2" },
      { min: 21, max: 30, label: "Sword, short +3" },
      { min: 31, max: 34, label: "Sword, normal +1" },
      { min: 35, max: 35, label: "Sword, normal +1, +3 vs dragonkind" },
      { min: 36, max: 36, label: "Sword, normal +1, +3 vs giantkind" },
      { min: 37, max: 37, label: "Sword, normal +1, +3 vs lycanthropes" },
      { min: 38, max: 38, label: "Sword, normal +1, +3 vs regenerating monsters" },
      { min: 39, max: 39, label: "Sword, normal +1, +3 vs spellcasters" },
      { min: 40, max: 40, label: "Sword, normal +1, +3 vs undead" },
      { min: 41, max: 50, label: "Sword, normal +2" },
      { min: 51, max: 60, label: "Sword, normal +3" },
      { min: 61, max: 64, label: "Sword, bastard +1" },
      { min: 65, max: 65, label: "Sword, bastard +1, +3 vs dragonkind" },
      { min: 66, max: 66, label: "Sword, bastard +1, +3 vs giantkind" },
      { min: 67, max: 67, label: "Sword, bastard +1, +3 vs lycanthropes" },
      { min: 68, max: 68, label: "Sword, bastard +1, +3 vs regenerating monsters" },
      { min: 69, max: 69, label: "Sword, bastard +1, +3 vs spellcasters" },
      { min: 70, max: 70, label: "Sword, bastard +1, +3 vs undead" },
      { min: 71, max: 75, label: "Sword, bastard +2" },
      { min: 76, max: 80, label: "Sword, bastard +3" },
      { min: 81, max: 84, label: "Sword, two-handed +1" },
      { min: 85, max: 85, label: "Sword, two-handed +1, +3 vs dragonkind" },
      { min: 86, max: 86, label: "Sword, two-handed +1, +3 vs giantkind" },
      { min: 87, max: 87, label: "Sword, two-handed +1, +3 vs lycanthropes" },
      { min: 88, max: 88, label: "Sword, two-handed +1, +3 vs regenerating monsters" },
      { min: 89, max: 89, label: "Sword, two-handed +1, +3 vs spellcasters" },
      { min: 90, max: 90, label: "Sword, two-handed +1, +3 vs undead" },
      { min: 91, max: 95, label: "Sword, two-handed +2" },
      { min: 96, max: 100, label: "Sword, two-handed +3" },
    ],
    miscWeapon: [
      { min: 1, max: 5, label: "Axe, battle +1" },
      { min: 6, max: 8, label: "Axe, battle +2" },
      { min: 9, max: 10, label: "Axe, battle +3" },
      { min: 11, max: 15, label: "Axe, hand +1" },
      { min: 16, max: 18, label: "Axe, hand +2" },
      { min: 19, max: 20, label: "Axe, hand +3" },
      { min: 21, max: 25, label: "Dagger +1" },
      { min: 26, max: 28, label: "Dagger +2" },
      { min: 29, max: 30, label: "Dagger +3" },
      { min: 31, max: 35, label: "Hammer, throwing +1" },
      { min: 36, max: 38, label: "Hammer, throwing +2" },
      { min: 39, max: 40, label: "Hammer, throwing +3" },
      { min: 41, max: 45, label: "Hammer, war +1" },
      { min: 46, max: 48, label: "Hammer, war +2" },
      { min: 49, max: 50, label: "Hammer, war +3" },
      { min: 51, max: 55, label: "Mace +1" },
      { min: 56, max: 58, label: "Mace +2" },
      { min: 59, max: 60, label: "Mace +3" },
      { min: 61, max: 65, label: "Polearm +1" },
      { min: 66, max: 68, label: "Polearm +2" },
      { min: 69, max: 70, label: "Polearm +3" },
      { min: 71, max: 72, label: "Shield, horned +1" },
      { min: 73, max: 75, label: "Shield, knife +1" },
      { min: 76, max: 78, label: "Shield, sword +1" },
      { min: 79, max: 80, label: "Shield, tusked +1" },
      { min: 81, max: 85, label: "Spear +1" },
      { min: 86, max: 88, label: "Spear +2" },
      { min: 89, max: 90, label: "Spear +3" },
      { min: 91, max: 95, label: "Staff +1" },
      { min: 96, max: 98, label: "Staff +2" },
      { min: 99, max: 100, label: "Staff +3" },
    ],
  };

  window.BECMI_TREASURE_DATA = data;
})();
