(function(){
  window.BECMI_ENCOUNTER_MONSTERS = [
  {
    "source": "Rules Cyclopedia",
    "name": "Ant, Giant",
    "ac": "3",
    "hd": "4*",
    "move": "180'",
    "attacks": "1 bite",
    "damage": "2d6+poison",
    "morale": "12",
    "treasureType": "U",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Ape, White/Snow",
    "ac": "6",
    "hd": "4",
    "move": "120'",
    "attacks": "2 claws",
    "damage": "1d4/1d4",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "75",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Basilisk",
    "ac": "4",
    "hd": "6+1**",
    "move": "60'",
    "attacks": "1 bite+gaze",
    "damage": "1d10+petrif",
    "morale": "9",
    "treasureType": "F",
    "xp": "950",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bat, Normal",
    "ac": "6",
    "hd": "1 hp",
    "move": "120'fly",
    "attacks": "confusion",
    "damage": "–",
    "morale": "6",
    "treasureType": "Nil",
    "xp": "–",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bat, Giant",
    "ac": "6",
    "hd": "2",
    "move": "180'fly",
    "attacks": "1 bite",
    "damage": "1d4",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bear, Black",
    "ac": "6",
    "hd": "4",
    "move": "120'",
    "attacks": "2 claws/bite",
    "damage": "1d3/1d3/1d6",
    "morale": "7",
    "treasureType": "U",
    "xp": "75",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bear, Grizzly",
    "ac": "6",
    "hd": "5",
    "move": "120'",
    "attacks": "2 claws/bite",
    "damage": "1d4/1d4/1d8",
    "morale": "8",
    "treasureType": "U",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bear, Cave",
    "ac": "5",
    "hd": "7",
    "move": "120'",
    "attacks": "2 claws/bite+hug",
    "damage": "1d8/1d8/2d6",
    "morale": "9",
    "treasureType": "V",
    "xp": "450",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Beetle, Fire",
    "ac": "4",
    "hd": "1+2",
    "move": "120'",
    "attacks": "1 bite",
    "damage": "2d4",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "15",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Beetle, Oil",
    "ac": "4",
    "hd": "2*",
    "move": "120'",
    "attacks": "1 bite+oil",
    "damage": "1d6+blistering",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Beetle, Tiger",
    "ac": "3",
    "hd": "3+1",
    "move": "150'",
    "attacks": "1 bite",
    "damage": "2d6",
    "morale": "9",
    "treasureType": "U",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Beholder",
    "ac": "0/7",
    "hd": "11**",
    "move": "30'",
    "attacks": "1 bite+eye rays",
    "damage": "2d8+specials",
    "morale": "10",
    "treasureType": "I,L,O",
    "xp": "3700",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Black Pudding",
    "ac": "6",
    "hd": "10*",
    "move": "60'",
    "attacks": "1",
    "damage": "3d8+dissolve",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "1750",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Blink Dog",
    "ac": "5",
    "hd": "4*",
    "move": "120'",
    "attacks": "1 bite",
    "damage": "1d6",
    "morale": "6",
    "treasureType": "C",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Bugbear",
    "ac": "5",
    "hd": "3+1",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "by weapon+1",
    "morale": "9",
    "treasureType": "B",
    "xp": "75",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Caecilia",
    "ac": "6",
    "hd": "6*",
    "move": "60'",
    "attacks": "1 bite",
    "damage": "1d8+swallow",
    "morale": "9",
    "treasureType": "B",
    "xp": "500",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Carrion Crawler",
    "ac": "7",
    "hd": "3+1*",
    "move": "120'",
    "attacks": "8 tentacles",
    "damage": "paralysis",
    "morale": "9",
    "treasureType": "B",
    "xp": "75",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Cat, Mountain Lion",
    "ac": "6",
    "hd": "3+2",
    "move": "150'",
    "attacks": "2 claws/bite",
    "damage": "1d3/1d3/1d6",
    "morale": "8",
    "treasureType": "U",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Cat, Panther",
    "ac": "4",
    "hd": "4",
    "move": "210'",
    "attacks": "2 claws/bite",
    "damage": "1d4/1d4/1d8",
    "morale": "8",
    "treasureType": "U",
    "xp": "75",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Cat, Sabre-Tooth",
    "ac": "6",
    "hd": "8",
    "move": "150'",
    "attacks": "2 claws/bite",
    "damage": "1d8/1d8/2d8",
    "morale": "10",
    "treasureType": "V",
    "xp": "650",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Centipede, Giant",
    "ac": "9",
    "hd": "½*",
    "move": "60'",
    "attacks": "1 bite",
    "damage": "poison(sicken)",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "6",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Chimera",
    "ac": "4",
    "hd": "9**",
    "move": "120'/180'fly",
    "attacks": "6 (claw/heads/breath)",
    "damage": "var+3d6 fire",
    "morale": "9",
    "treasureType": "F",
    "xp": "2300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Cockatrice",
    "ac": "6",
    "hd": "5**",
    "move": "90'/180'fly",
    "attacks": "1 beak",
    "damage": "1d6+petrif",
    "morale": "7",
    "treasureType": "D",
    "xp": "425",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Crab, Giant",
    "ac": "2",
    "hd": "3",
    "move": "60'",
    "attacks": "2 pincers",
    "damage": "2d6/2d6",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "35",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Crocodile, Normal",
    "ac": "5",
    "hd": "2",
    "move": "90'/90'swim",
    "attacks": "1 bite",
    "damage": "1d8",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Crocodile, Large",
    "ac": "3",
    "hd": "6",
    "move": "90'/90'swim",
    "attacks": "1 bite",
    "damage": "2d8",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "275",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Crocodile, Giant",
    "ac": "1",
    "hd": "15",
    "move": "90'/90'swim",
    "attacks": "1 bite",
    "damage": "3d8",
    "morale": "9",
    "treasureType": "Nil",
    "xp": "1350",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Cyclops",
    "ac": "5",
    "hd": "13*",
    "move": "90'",
    "attacks": "1 club",
    "damage": "3d10",
    "morale": "9",
    "treasureType": "E+5000gp",
    "xp": "2300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Displacer Beast",
    "ac": "4",
    "hd": "6*",
    "move": "150'",
    "attacks": "2 tentacles",
    "damage": "2d4/2d4",
    "morale": "8",
    "treasureType": "D",
    "xp": "500",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Djinni",
    "ac": "5",
    "hd": "7+1**",
    "move": "90'/240'fly",
    "attacks": "1 fist/whirlwind",
    "damage": "2d8",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "1250",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Doppleganger",
    "ac": "5",
    "hd": "4*",
    "move": "90'",
    "attacks": "1",
    "damage": "1d12",
    "morale": "10",
    "treasureType": "E",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Dragon Turtle",
    "ac": "0",
    "hd": "30**",
    "move": "60'/90'swim",
    "attacks": "2 claw/bite/breath",
    "damage": "var/steam",
    "morale": "10",
    "treasureType": "H×2",
    "xp": "spec",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Dryad",
    "ac": "5",
    "hd": "2**",
    "move": "120'",
    "attacks": "charm",
    "damage": "charm person",
    "morale": "6",
    "treasureType": "D",
    "xp": "30",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Dwarf",
    "ac": "4",
    "hd": "1",
    "move": "60'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "8/10",
    "treasureType": "G",
    "xp": "10",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Efreeti",
    "ac": "3",
    "hd": "10**",
    "move": "90'/240'fly",
    "attacks": "1 fist",
    "damage": "2d8",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "2500",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Elemental (Air)",
    "ac": "-2",
    "hd": "8/12/16*",
    "move": "360'fly",
    "attacks": "1",
    "damage": "1d8/2d8/3d8",
    "morale": "10",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Elemental (Earth)",
    "ac": "-2",
    "hd": "8/12/16*",
    "move": "60'",
    "attacks": "1",
    "damage": "1d8/2d8/3d8",
    "morale": "10",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Elemental (Fire)",
    "ac": "-2",
    "hd": "8/12/16*",
    "move": "120'",
    "attacks": "1",
    "damage": "1d8/2d8/3d8",
    "morale": "10",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Elemental (Water)",
    "ac": "-2",
    "hd": "8/12/16*",
    "move": "60'/180'swim",
    "attacks": "1",
    "damage": "1d8/2d8/3d8",
    "morale": "10",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Elf",
    "ac": "5",
    "hd": "1+1*",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "8/10",
    "treasureType": "E",
    "xp": "19",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Ferret, Giant",
    "ac": "5",
    "hd": "1+1",
    "move": "150'",
    "attacks": "1 bite",
    "damage": "1d8",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "15",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Fish, Giant (Cat/Pir/Rock/Stur)",
    "ac": "var",
    "hd": "8–21",
    "move": "swim",
    "attacks": "1 bite",
    "damage": "var",
    "morale": "var",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gargoyle",
    "ac": "5",
    "hd": "4**",
    "move": "90'/150'fly",
    "attacks": "2 claw/bite/horn",
    "damage": "1d4/1d4/1d6/1d4",
    "morale": "11",
    "treasureType": "C",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gelatinous Cube",
    "ac": "8",
    "hd": "4*",
    "move": "60'",
    "attacks": "1",
    "damage": "2d4+paralysis",
    "morale": "12",
    "treasureType": "V",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Ghoul",
    "ac": "6",
    "hd": "2*",
    "move": "90'",
    "attacks": "2 claw/bite",
    "damage": "1d3/1d3/1d3+paralysis",
    "morale": "9",
    "treasureType": "B",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Hill",
    "ac": "4",
    "hd": "8",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "2d8",
    "morale": "8",
    "treasureType": "E+5000gp",
    "xp": "650",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Stone",
    "ac": "4",
    "hd": "9",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "3d6",
    "morale": "9",
    "treasureType": "E+5000gp",
    "xp": "900",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Frost",
    "ac": "4",
    "hd": "10+1",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "4d6",
    "morale": "9",
    "treasureType": "E+5000gp",
    "xp": "1350",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Fire",
    "ac": "4",
    "hd": "11+2",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "5d6",
    "morale": "9",
    "treasureType": "E+5000gp",
    "xp": "1700",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Cloud",
    "ac": "4",
    "hd": "12+2",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "6d6",
    "morale": "10",
    "treasureType": "E+5000gp",
    "xp": "2125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Giant, Storm",
    "ac": "2",
    "hd": "15**",
    "move": "150'",
    "attacks": "1 weapon+lightning",
    "damage": "8d6/15d6 bolt",
    "morale": "10",
    "treasureType": "E+5000gp",
    "xp": "2725",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gnoll",
    "ac": "5",
    "hd": "2",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "by weapon+1",
    "morale": "8",
    "treasureType": "D,P",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gnome",
    "ac": "5",
    "hd": "1",
    "move": "60'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "8",
    "treasureType": "C",
    "xp": "10",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Goblin",
    "ac": "6",
    "hd": "1-1",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "7/9",
    "treasureType": "R,C",
    "xp": "5",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Golem (Wood)",
    "ac": "7",
    "hd": "2+2*",
    "move": "120'",
    "attacks": "1 fist",
    "damage": "1d8",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "35",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Golem (Bone)",
    "ac": "2",
    "hd": "6*",
    "move": "120'",
    "attacks": "4 weapons",
    "damage": "1d6 each",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "500",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Golem (Amber)",
    "ac": "6",
    "hd": "10*",
    "move": "180'",
    "attacks": "2 claw/bite",
    "damage": "2d6/2d6/2d10",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "1750",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Golem (Bronze)",
    "ac": "0",
    "hd": "20**",
    "move": "240'",
    "attacks": "1 fist",
    "damage": "3d10+fire",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "5975",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gorgon",
    "ac": "2",
    "hd": "8*",
    "move": "120'",
    "attacks": "1 horn/breath",
    "damage": "2d6/petrif",
    "morale": "8",
    "treasureType": "E",
    "xp": "1200",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Gray Ooze",
    "ac": "8",
    "hd": "3*",
    "move": "10'",
    "attacks": "1",
    "damage": "2d8+dissolve",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Green Slime",
    "ac": "9",
    "hd": "2**",
    "move": "3'",
    "attacks": "1 drip",
    "damage": "dissolve→slime",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "30",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Griffon",
    "ac": "5",
    "hd": "7",
    "move": "120'/360'fly",
    "attacks": "2 claw/bite",
    "damage": "1d4/1d4/2d8",
    "morale": "8",
    "treasureType": "E",
    "xp": "450",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Halfling",
    "ac": "7",
    "hd": "1-1",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "7/10",
    "treasureType": "var",
    "xp": "5",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Harpy",
    "ac": "7",
    "hd": "3*",
    "move": "60'/150'fly",
    "attacks": "2 claw/weapon+song",
    "damage": "1d4/1d4/1d6+charm",
    "morale": "7",
    "treasureType": "C",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Hellhound",
    "ac": "4",
    "hd": "3–7*",
    "move": "120'",
    "attacks": "1 bite+breath",
    "damage": "1d6+fire (per HD)",
    "morale": "9",
    "treasureType": "C",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Hippogriff",
    "ac": "5",
    "hd": "3+1",
    "move": "180'/360'fly",
    "attacks": "2 claw/bite",
    "damage": "1d6/1d6/1d10",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Hobgoblin",
    "ac": "6",
    "hd": "1+1",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "8/10",
    "treasureType": "D",
    "xp": "15",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Horse (various)",
    "ac": "var",
    "hd": "2–3",
    "move": "240'",
    "attacks": "2 hooves(/bite)",
    "damage": "1d4/1d4",
    "morale": "7–9",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Hydra",
    "ac": "5",
    "hd": "5–12",
    "move": "120'",
    "attacks": "5–12 bites",
    "damage": "1d10 each",
    "morale": "11",
    "treasureType": "B",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Insect Swarm",
    "ac": "7",
    "hd": "2–4*",
    "move": "30'/60'fly",
    "attacks": "1 swarm",
    "damage": "2/4 hp",
    "morale": "11",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Invisible Stalker",
    "ac": "3",
    "hd": "8*",
    "move": "120'",
    "attacks": "1",
    "damage": "4d4",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "1200",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Kobold",
    "ac": "7",
    "hd": "½",
    "move": "60'",
    "attacks": "1 weapon",
    "damage": "by weapon-1",
    "morale": "6/8",
    "treasureType": "J,P",
    "xp": "5",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Leech, Giant",
    "ac": "7",
    "hd": "6",
    "move": "90'",
    "attacks": "1 bite",
    "damage": "1d6+drain",
    "morale": "10",
    "treasureType": "Nil",
    "xp": "275",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Lich*",
    "ac": "0",
    "hd": "21+***",
    "move": "60'",
    "attacks": "1 touch+spells",
    "damage": "2d8+paralysis",
    "morale": "10",
    "treasureType": "A",
    "xp": "7500+",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Living Statue (var)",
    "ac": "4",
    "hd": "3–5*",
    "move": "30'–90'",
    "attacks": "2",
    "damage": "var",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Lizard, Giant (var)",
    "ac": "2–5",
    "hd": "3–6",
    "move": "120'",
    "attacks": "var",
    "damage": "var",
    "morale": "7",
    "treasureType": "U/V",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Lizard Man",
    "ac": "5",
    "hd": "2+1",
    "move": "60'/120'swim",
    "attacks": "1 weapon",
    "damage": "by weapon+1",
    "morale": "12",
    "treasureType": "D",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Locust, Giant",
    "ac": "4",
    "hd": "2",
    "move": "60'/180'fly",
    "attacks": "bite/bump/spit",
    "damage": "1d2–1d4+stink",
    "morale": "5",
    "treasureType": "Nil",
    "xp": "30",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Lycanthrope (5 typer)",
    "ac": "7–9",
    "hd": "3–5*",
    "move": "120'–180'",
    "attacks": "var",
    "damage": "var+lycanthropy",
    "morale": "8–9",
    "treasureType": "C",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Manticore",
    "ac": "4",
    "hd": "6+1",
    "move": "120'/180'fly",
    "attacks": "2 claw/bite/6 spikes",
    "damage": "1d4/1d4/2d4/1d6×6",
    "morale": "9",
    "treasureType": "D",
    "xp": "275",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Medusa",
    "ac": "8",
    "hd": "4**",
    "move": "90'",
    "attacks": "1 snakebite+gaze",
    "damage": "1d6+poison/petrif",
    "morale": "8",
    "treasureType": "F",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Minotaur",
    "ac": "6",
    "hd": "6",
    "move": "120'",
    "attacks": "butt/bite/weapon",
    "damage": "1d6/1d6/by weapon",
    "morale": "12",
    "treasureType": "C",
    "xp": "275",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Mummy*",
    "ac": "3",
    "hd": "5+1**",
    "move": "60'",
    "attacks": "1 touch",
    "damage": "1d12+disease",
    "morale": "12",
    "treasureType": "D",
    "xp": "575",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Neanderthal",
    "ac": "8",
    "hd": "2",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "by weapon+1",
    "morale": "7",
    "treasureType": "C",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Nixie",
    "ac": "7",
    "hd": "1*",
    "move": "120'swim",
    "attacks": "1 weapon/charm",
    "damage": "by weapon",
    "morale": "6",
    "treasureType": "B",
    "xp": "13",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Nuckalavee",
    "ac": "2",
    "hd": "10***",
    "move": "120'/180'swim",
    "attacks": "1 claw+breath",
    "damage": "1d8+death ray/cold",
    "morale": "10",
    "treasureType": "E",
    "xp": "3500",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Ochre Jelly",
    "ac": "8",
    "hd": "5*",
    "move": "30'",
    "attacks": "1",
    "damage": "2d8+dissolve",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Ogre",
    "ac": "5",
    "hd": "4+1",
    "move": "90'",
    "attacks": "1 club",
    "damage": "by weapon+2",
    "morale": "10",
    "treasureType": "S×10,C",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Orc",
    "ac": "6",
    "hd": "1",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "6/8",
    "treasureType": "D,P",
    "xp": "10",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Owl Bear",
    "ac": "5",
    "hd": "5",
    "move": "120'",
    "attacks": "2 claw/bite+hug",
    "damage": "1d8/1d8/1d8",
    "morale": "9",
    "treasureType": "C",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Pegasus",
    "ac": "5",
    "hd": "2+2",
    "move": "240'/480'fly",
    "attacks": "2 hooves",
    "damage": "1d6/1d6",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Pixie",
    "ac": "3",
    "hd": "1*",
    "move": "90'/180'fly",
    "attacks": "1 dagger/spell",
    "damage": "1d4+invis",
    "morale": "7",
    "treasureType": "R,S",
    "xp": "13",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Purple Worm",
    "ac": "6",
    "hd": "15*",
    "move": "60'",
    "attacks": "1 bite/1 sting",
    "damage": "2d8/1d8+poison",
    "morale": "10",
    "treasureType": "D×3",
    "xp": "2725",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Rat, Normal",
    "ac": "9",
    "hd": "1 hp",
    "move": "60'/30'swim",
    "attacks": "1 bite/pack",
    "damage": "1d6+disease(5%)",
    "morale": "5",
    "treasureType": "L",
    "xp": "–",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Rat, Giant",
    "ac": "7",
    "hd": "½",
    "move": "120'/60'swim",
    "attacks": "1 bite",
    "damage": "1d3+disease(5%)",
    "morale": "8",
    "treasureType": "C",
    "xp": "6",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Robber Fly",
    "ac": "6",
    "hd": "2",
    "move": "90'/180'fly",
    "attacks": "1 bite",
    "damage": "1d8",
    "morale": "8",
    "treasureType": "U",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Rust Monster",
    "ac": "2",
    "hd": "5*",
    "move": "120'",
    "attacks": "1 touch",
    "damage": "rust destroy",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Salamander (fire)",
    "ac": "2",
    "hd": "8*",
    "move": "120'",
    "attacks": "2 claw/bite+heat",
    "damage": "1d4/1d4/1d8+heat",
    "morale": "8",
    "treasureType": "F",
    "xp": "1200",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Salamander (frost)",
    "ac": "3",
    "hd": "12*",
    "move": "120'",
    "attacks": "4 claw/bite+cold",
    "damage": "var+cold aura",
    "morale": "9",
    "treasureType": "E",
    "xp": "2700",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Scorpion, Giant",
    "ac": "2",
    "hd": "4*",
    "move": "150'",
    "attacks": "2 pincers/sting",
    "damage": "1d10/1d10/1d4+poison",
    "morale": "11",
    "treasureType": "V",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Shadow",
    "ac": "7",
    "hd": "2+2*",
    "move": "90'",
    "attacks": "1 touch",
    "damage": "1d4+STR drain",
    "morale": "12",
    "treasureType": "F",
    "xp": "35",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Shark",
    "ac": "4",
    "hd": "4–8",
    "move": "180'swim",
    "attacks": "1 bite",
    "damage": "2d4–2d10",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "var",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Shrieker",
    "ac": "7",
    "hd": "3",
    "move": "9'",
    "attacks": "shriek",
    "damage": "attracts monsters",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "35",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Skeleton",
    "ac": "7",
    "hd": "1",
    "move": "60'",
    "attacks": "1 weapon",
    "damage": "by weapon",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "10",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Snake, Cobra",
    "ac": "7",
    "hd": "1*",
    "move": "90'",
    "attacks": "1 bite",
    "damage": "1d3+poison",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "13",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Snake, Python",
    "ac": "6",
    "hd": "5*",
    "move": "90'",
    "attacks": "1 bite+squeeze",
    "damage": "1d4+2d4/rd",
    "morale": "8",
    "treasureType": "U",
    "xp": "300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Snake, Viper",
    "ac": "8",
    "hd": "½* (2*)+",
    "move": "90'",
    "attacks": "1 bite",
    "damage": "poison",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "6–25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Spectre*",
    "ac": "2",
    "hd": "6**",
    "move": "150'/300'fly",
    "attacks": "1 touch",
    "damage": "1d8+energy drain(2)",
    "morale": "11",
    "treasureType": "E",
    "xp": "725",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Spider, Crab",
    "ac": "7",
    "hd": "2*",
    "move": "120'",
    "attacks": "1 bite",
    "damage": "1d8+poison",
    "morale": "7",
    "treasureType": "U",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Spider, Tarantella",
    "ac": "5",
    "hd": "4*",
    "move": "120'",
    "attacks": "1 bite",
    "damage": "1d8+dance poison",
    "morale": "8",
    "treasureType": "U",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Sprite",
    "ac": "5",
    "hd": "½*",
    "move": "60'/180'fly",
    "attacks": "1 curse/spell",
    "damage": "special",
    "morale": "7",
    "treasureType": "S",
    "xp": "6",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Stirge",
    "ac": "7",
    "hd": "1*",
    "move": "30'/180'fly",
    "attacks": "1 jab",
    "damage": "1d3+1d3/rd drain",
    "morale": "9",
    "treasureType": "L",
    "xp": "13",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Thoul",
    "ac": "6",
    "hd": "3**",
    "move": "120'",
    "attacks": "2 claw/paralysis",
    "damage": "1d3/1d3+paralysis",
    "morale": "10",
    "treasureType": "C",
    "xp": "65",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Toad, Giant",
    "ac": "7",
    "hd": "2+2",
    "move": "90'",
    "attacks": "1 bite",
    "damage": "1d4+1+swallow",
    "morale": "6",
    "treasureType": "Nil",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Treant",
    "ac": "2",
    "hd": "8*",
    "move": "60'",
    "attacks": "2 branches",
    "damage": "2d6/2d6",
    "morale": "9",
    "treasureType": "C",
    "xp": "1200",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Troglodyte",
    "ac": "5",
    "hd": "2*",
    "move": "120'",
    "attacks": "2 claw/bite+stench",
    "damage": "1d4/1d4/1d4",
    "morale": "9",
    "treasureType": "A",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Troll",
    "ac": "4",
    "hd": "6+3*",
    "move": "120'",
    "attacks": "2 claw/bite",
    "damage": "1d6/1d6/1d10",
    "morale": "10",
    "treasureType": "D",
    "xp": "650",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Unicorn",
    "ac": "2",
    "hd": "4**",
    "move": "240'",
    "attacks": "2 hooves/horn",
    "damage": "1d8/1d8/1d8",
    "morale": "7",
    "treasureType": "Nil",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Vampire*",
    "ac": "2",
    "hd": "7–9**",
    "move": "120'/180'fly",
    "attacks": "1 touch+gaze",
    "damage": "1d10+energy drain(2)",
    "morale": "11",
    "treasureType": "F",
    "xp": "1250–2300",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Wight*",
    "ac": "5",
    "hd": "3*",
    "move": "90'",
    "attacks": "1 touch",
    "damage": "energy drain(1)",
    "morale": "12",
    "treasureType": "B",
    "xp": "50",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Wolf, Normal",
    "ac": "7",
    "hd": "2+2",
    "move": "180'",
    "attacks": "1 bite",
    "damage": "1d6",
    "morale": "6/8",
    "treasureType": "Nil",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Wolf, Dire",
    "ac": "6",
    "hd": "4+1",
    "move": "150'",
    "attacks": "1 bite",
    "damage": "2d4",
    "morale": "8",
    "treasureType": "Nil",
    "xp": "125",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Wraith*",
    "ac": "3",
    "hd": "4**",
    "move": "120'/240'fly",
    "attacks": "1 touch",
    "damage": "1d6+energy drain(1)",
    "morale": "11",
    "treasureType": "E",
    "xp": "175",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Wyvern",
    "ac": "3",
    "hd": "7*",
    "move": "90'/240'fly",
    "attacks": "1 bite/1 sting",
    "damage": "2d8/1d6+poison",
    "morale": "9",
    "treasureType": "E",
    "xp": "850",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Yellow Mold",
    "ac": "9",
    "hd": "2*",
    "move": "0",
    "attacks": "spore cloud",
    "damage": "1d6+spores(death)",
    "morale": "N/A",
    "treasureType": "Nil",
    "xp": "25",
    "monsterType": ""
  },
  {
    "source": "Rules Cyclopedia",
    "name": "Zombie",
    "ac": "8",
    "hd": "2",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "1d8",
    "morale": "12",
    "treasureType": "Nil",
    "xp": "20",
    "monsterType": ""
  },
  {
    "source": "Creature Catalog",
    "name": "Amber Lotus Flower",
    "ac": "9",
    "hd": "½",
    "move": "0",
    "attacks": "1 spray",
    "damage": "Special (søvn)",
    "morale": "12",
    "treasureType": "",
    "xp": "6",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Amoeba, Giant",
    "ac": "9",
    "hd": "10–15*",
    "move": "30'",
    "attacks": "1 acid touch",
    "damage": "2d6",
    "morale": "10",
    "treasureType": "",
    "xp": "1000–1650",
    "monsterType": "Lowlife (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Aranea",
    "ac": "7",
    "hd": "3**",
    "move": "60'/web",
    "attacks": "1 bite",
    "damage": "1d6+gift",
    "morale": "7",
    "treasureType": "",
    "xp": "65",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Archer Bush",
    "ac": "7",
    "hd": "3",
    "move": "0",
    "attacks": "4 thorns",
    "damage": "1d6 each",
    "morale": "12",
    "treasureType": "",
    "xp": "35",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Ash Crawler",
    "ac": "3",
    "hd": "6+1*",
    "move": "120'",
    "attacks": "2 claws",
    "damage": "1d8/1d8+drain",
    "morale": "10",
    "treasureType": "",
    "xp": "950",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Baldandar",
    "ac": "-2",
    "hd": "15***",
    "move": "120'",
    "attacks": "2 fists/breath",
    "damage": "3d6/3d6/special",
    "morale": "10",
    "treasureType": "",
    "xp": "5850",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Banshee, Lesser",
    "ac": "0",
    "hd": "7**",
    "move": "150' fly",
    "attacks": "1 wail",
    "damage": "Special (death)",
    "morale": "10",
    "treasureType": "",
    "xp": "1250",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Bargda",
    "ac": "6",
    "hd": "4+1",
    "move": "90'",
    "attacks": "3 (2 claws/bite)",
    "damage": "1d4/1d4/1d8",
    "morale": "9",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Beetle, Earthquake",
    "ac": "1",
    "hd": "12*",
    "move": "120'/60' burrow",
    "attacks": "1 bite",
    "damage": "4d6",
    "morale": "10",
    "treasureType": "",
    "xp": "2125",
    "monsterType": "Giant Animal (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Beholder, Aquatic",
    "ac": "0",
    "hd": "11**",
    "move": "30'/90'swim",
    "attacks": "1 bite+eyestalks",
    "damage": "2d8+specials",
    "morale": "10",
    "treasureType": "",
    "xp": "3700",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Bhut",
    "ac": "5",
    "hd": "3*",
    "move": "90'",
    "attacks": "1 claw",
    "damage": "1d6+paralysis",
    "morale": "11",
    "treasureType": "",
    "xp": "50",
    "monsterType": "Undead (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Brain Collector",
    "ac": "0",
    "hd": "10***",
    "move": "120'",
    "attacks": "1 bite+spells",
    "damage": "2d4+level drain",
    "morale": "9",
    "treasureType": "",
    "xp": "5000",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Brownie",
    "ac": "3",
    "hd": "1*",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "7",
    "treasureType": "",
    "xp": "13",
    "monsterType": "Enchanted (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Chameleon Man",
    "ac": "4",
    "hd": "5*",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon+1",
    "morale": "8",
    "treasureType": "",
    "xp": "300",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Chevall",
    "ac": "2",
    "hd": "7+1**",
    "move": "240'",
    "attacks": "2 hooves/1 bite",
    "damage": "1d8/1d8/1d4",
    "morale": "9",
    "treasureType": "",
    "xp": "1250",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Choker",
    "ac": "5",
    "hd": "3+1",
    "move": "90'",
    "attacks": "2 tentacles",
    "damage": "1d4/1d4+strangle",
    "morale": "10",
    "treasureType": "",
    "xp": "75",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Coltpixy",
    "ac": "5",
    "hd": "½**",
    "move": "180' fly",
    "attacks": "1 spell",
    "damage": "Special",
    "morale": "7",
    "treasureType": "",
    "xp": "7",
    "monsterType": "Enchanted (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Crone of Chaos",
    "ac": "-2",
    "hd": "20****",
    "move": "120'",
    "attacks": "2+spell",
    "damage": "2d10+special",
    "morale": "11",
    "treasureType": "",
    "xp": "13500",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Cryion",
    "ac": "2",
    "hd": "8**",
    "move": "120'",
    "attacks": "1 slam+cold",
    "damage": "2d8+1d8 cold",
    "morale": "9",
    "treasureType": "",
    "xp": "1750",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dark Wing",
    "ac": "3",
    "hd": "4+4",
    "move": "30'/240'fly",
    "attacks": "1 bite",
    "damage": "2d6",
    "morale": "9",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Monster (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Darkhood (Rorphyr)",
    "ac": "0",
    "hd": "10***",
    "move": "90'",
    "attacks": "1 envelop",
    "damage": "2d6+suffocation",
    "morale": "11",
    "treasureType": "",
    "xp": "3500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Death Fiend (Ostego)",
    "ac": "-2",
    "hd": "14****",
    "move": "150'/240'fly",
    "attacks": "2 claws/bite",
    "damage": "2d8/2d8/3d6+drain",
    "morale": "11",
    "treasureType": "",
    "xp": "7100",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Decapus (Land)",
    "ac": "5",
    "hd": "4*",
    "move": "90'",
    "attacks": "8 tentacles",
    "damage": "1d4 each",
    "morale": "8",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Deep Glaurant",
    "ac": "0",
    "hd": "9**",
    "move": "120'/60'swim",
    "attacks": "2 claws/bite",
    "damage": "1d8/1d8/2d6",
    "morale": "10",
    "treasureType": "",
    "xp": "2300",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Desert Ghost",
    "ac": "2",
    "hd": "7**",
    "move": "60'/180'fly",
    "attacks": "1 touch",
    "damage": "2d6+energy drain",
    "morale": "11",
    "treasureType": "",
    "xp": "1250",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dragon, Pocket",
    "ac": "5",
    "hd": "1",
    "move": "60'/180'fly",
    "attacks": "1 bite",
    "damage": "1d4",
    "morale": "8",
    "treasureType": "",
    "xp": "10",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dragon, Sea",
    "ac": "variabel",
    "hd": "5–12",
    "move": "Swim var.",
    "attacks": "2 claw/bite/breath",
    "damage": "Variable",
    "morale": "10",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dragon, Undead",
    "ac": "variabel",
    "hd": "som levende",
    "move": "som levende",
    "attacks": "2 claw/bite",
    "damage": "som levende+drain",
    "morale": "12",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dragonne",
    "ac": "2",
    "hd": "9**",
    "move": "150'/90'fly",
    "attacks": "2 claws/bite+roar",
    "damage": "1d8/1d8/3d6+fear",
    "morale": "10",
    "treasureType": "",
    "xp": "2300",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Dusanu",
    "ac": "3",
    "hd": "6**",
    "move": "120'",
    "attacks": "1 touch",
    "damage": "2d8+disease",
    "morale": "11",
    "treasureType": "",
    "xp": "725",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Elf, Aquatic",
    "ac": "5",
    "hd": "1+1*",
    "move": "120'swim",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "8",
    "treasureType": "",
    "xp": "19",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Faedorne",
    "ac": "-2",
    "hd": "12***",
    "move": "240'fly",
    "attacks": "1 sword+spell",
    "damage": "2d8+5+spells",
    "morale": "11",
    "treasureType": "",
    "xp": "5600",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Feywing",
    "ac": "3",
    "hd": "2**",
    "move": "120'fly",
    "attacks": "1 bite/spell",
    "damage": "1d6+special",
    "morale": "7",
    "treasureType": "",
    "xp": "30",
    "monsterType": "Enchanted (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Fungoid",
    "ac": "8",
    "hd": "1–3",
    "move": "60'",
    "attacks": "1 weapon/spore",
    "damage": "By weapon/special",
    "morale": "8",
    "treasureType": "",
    "xp": "10–35",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Fyrsnaca",
    "ac": "2",
    "hd": "8**",
    "move": "120'",
    "attacks": "1 bite+fire",
    "damage": "2d8+2d6 fire",
    "morale": "10",
    "treasureType": "",
    "xp": "1750",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Gakarak",
    "ac": "6",
    "hd": "6+2*",
    "move": "60'",
    "attacks": "2 claws/bite",
    "damage": "1d8/1d8/2d6",
    "morale": "10",
    "treasureType": "",
    "xp": "725",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Gargoyle, Iron",
    "ac": "-2",
    "hd": "8***",
    "move": "60'/150'fly",
    "attacks": "2 claws/horn",
    "damage": "1d8/1d8/2d6",
    "morale": "11",
    "treasureType": "",
    "xp": "2500",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Gator Man",
    "ac": "5",
    "hd": "3+1",
    "move": "90'/120'swim",
    "attacks": "1 bite/weapon",
    "damage": "2d4/by weapon",
    "morale": "8",
    "treasureType": "",
    "xp": "50",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Geonid",
    "ac": "-4 (lukket)/5",
    "hd": "2",
    "move": "30'",
    "attacks": "1 club",
    "damage": "1d8",
    "morale": "8",
    "treasureType": "",
    "xp": "20",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Ghoul, Elder",
    "ac": "2",
    "hd": "5**",
    "move": "120'",
    "attacks": "2 claws/bite",
    "damage": "1d6/1d6/1d8+paralysis",
    "morale": "11",
    "treasureType": "",
    "xp": "425",
    "monsterType": "Undead (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Ghostly Horde",
    "ac": "-",
    "hd": "Special",
    "move": "120'",
    "attacks": "Panic",
    "damage": "Fear/death",
    "morale": "12",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Golem (Mud/Obsidian)",
    "ac": "variabel",
    "hd": "5–12*",
    "move": "variable",
    "attacks": "1–2",
    "damage": "variable",
    "morale": "12",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Enchanted"
  },
  {
    "source": "Creature Catalog",
    "name": "Gray Philosopher",
    "ac": "-2",
    "hd": "10***",
    "move": "0 (stationary)",
    "attacks": "malice spirits",
    "damage": "Special",
    "morale": "12",
    "treasureType": "",
    "xp": "3500",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Haunt, Lesser",
    "ac": "4",
    "hd": "4**",
    "move": "0",
    "attacks": "1 touch",
    "damage": "1d6+age 1d10 years",
    "morale": "12",
    "treasureType": "",
    "xp": "175",
    "monsterType": "Undead (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Hephaeston",
    "ac": "-4",
    "hd": "20****",
    "move": "150'",
    "attacks": "2 fists+breath",
    "damage": "3d10/3d10+fire",
    "morale": "11",
    "treasureType": "",
    "xp": "13500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Herex",
    "ac": "3",
    "hd": "2+1",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "9",
    "treasureType": "",
    "xp": "25",
    "monsterType": "Humanoid (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Hivebrood",
    "ac": "variabel",
    "hd": "1–8",
    "move": "variable",
    "attacks": "variable",
    "damage": "variable",
    "morale": "12",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Hutaakan",
    "ac": "6",
    "hd": "2",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "7",
    "treasureType": "",
    "xp": "20",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Hypnosnake",
    "ac": "6",
    "hd": "3**",
    "move": "90'",
    "attacks": "1 bite+charm",
    "damage": "1d4+charm gaze",
    "morale": "8",
    "treasureType": "",
    "xp": "65",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Ice Wolf",
    "ac": "6",
    "hd": "4**",
    "move": "180'",
    "attacks": "1 bite",
    "damage": "2d4+cold breath",
    "morale": "9",
    "treasureType": "",
    "xp": "175",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Juggernaut",
    "ac": "0",
    "hd": "10*",
    "move": "60'",
    "attacks": "1 crush",
    "damage": "10d6",
    "morale": "12",
    "treasureType": "",
    "xp": "1600",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Kal-Muru (Shipbane)",
    "ac": "2",
    "hd": "12***",
    "move": "180'swim",
    "attacks": "4 tentacles+bite",
    "damage": "2d6 each+3d10",
    "morale": "10",
    "treasureType": "",
    "xp": "5600",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Kara-Kara",
    "ac": "7",
    "hd": "1",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "7",
    "treasureType": "",
    "xp": "10",
    "monsterType": "Humanoid (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Killer Tree",
    "ac": "0",
    "hd": "10*",
    "move": "0",
    "attacks": "4 branches",
    "damage": "2d6 each",
    "morale": "12",
    "treasureType": "",
    "xp": "1600",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Kna",
    "ac": "4",
    "hd": "1+1",
    "move": "90'/180'swim",
    "attacks": "1 weapon",
    "damage": "By weapon+1",
    "morale": "8",
    "treasureType": "",
    "xp": "15",
    "monsterType": "Humanoid (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Kopru",
    "ac": "3",
    "hd": "8+4**",
    "move": "30'/180'swim",
    "attacks": "3 (2 tail/bite)",
    "damage": "1d6/1d6/1d4+charm",
    "morale": "9",
    "treasureType": "",
    "xp": "2300",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Kraken",
    "ac": "0",
    "hd": "20****",
    "move": "30'/180'swim",
    "attacks": "8 tentacles/bite",
    "damage": "2d8 each/10d4",
    "morale": "10",
    "treasureType": "",
    "xp": "13500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Lamara",
    "ac": "5",
    "hd": "4*",
    "move": "90'/120'swim",
    "attacks": "1 bite+constrict",
    "damage": "1d8+1d6/round",
    "morale": "9",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Lava Lizard",
    "ac": "2",
    "hd": "5**",
    "move": "60'/120'swim(lava)",
    "attacks": "1 bite+spit",
    "damage": "2d6+2d6 fire",
    "morale": "10",
    "treasureType": "",
    "xp": "425",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Leviathan",
    "ac": "-4",
    "hd": "30****",
    "move": "180'swim",
    "attacks": "1 bite/1 tail",
    "damage": "10d6/10d6",
    "morale": "11",
    "treasureType": "",
    "xp": "30000+",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Lupin",
    "ac": "6",
    "hd": "1+1",
    "move": "120'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "8",
    "treasureType": "",
    "xp": "15",
    "monsterType": "Humanoid (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Magen (Galvan/Demos/Caldron/Hypnos)",
    "ac": "var.",
    "hd": "3–8*",
    "move": "variable",
    "attacks": "variable",
    "damage": "variable",
    "morale": "12",
    "treasureType": "",
    "xp": "var.",
    "monsterType": "Enchanted"
  },
  {
    "source": "Creature Catalog",
    "name": "Mesmer",
    "ac": "0",
    "hd": "10**",
    "move": "30'/120'swim",
    "attacks": "1 touch",
    "damage": "1d8+charm aura",
    "morale": "10",
    "treasureType": "",
    "xp": "2500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Nagpa",
    "ac": "0",
    "hd": "14***",
    "move": "120'",
    "attacks": "1 staff+spell",
    "damage": "1d8+spells (niv 12 MU)",
    "morale": "9",
    "treasureType": "",
    "xp": "5250",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Nightmare",
    "ac": "-2",
    "hd": "12***",
    "move": "180'/360'fly",
    "attacks": "2 hooves/bite",
    "damage": "2d8/2d8/2d6+fire",
    "morale": "11",
    "treasureType": "",
    "xp": "5600",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Owl, Giant",
    "ac": "5",
    "hd": "4",
    "move": "30'/240'fly",
    "attacks": "2 talons/bite",
    "damage": "1d8/1d8/2d6",
    "morale": "8",
    "treasureType": "",
    "xp": "75",
    "monsterType": "Giant Animal (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Pachydermion",
    "ac": "4",
    "hd": "7*",
    "move": "120'",
    "attacks": "2 fists/tusks",
    "damage": "1d8/1d8/2d6",
    "morale": "9",
    "treasureType": "",
    "xp": "850",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Pegataur",
    "ac": "var.",
    "hd": "4+4",
    "move": "180'/360'fly",
    "attacks": "2 hooves/weapon",
    "damage": "1d6/1d6+weapon",
    "morale": "8",
    "treasureType": "",
    "xp": "200",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Phanaton",
    "ac": "7",
    "hd": "1-1",
    "move": "90'/150'glide",
    "attacks": "1 weapon",
    "damage": "1d6/weapon",
    "morale": "7",
    "treasureType": "",
    "xp": "5",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Phantom, Lesser",
    "ac": "9",
    "hd": "6**",
    "move": "120'/240'fly",
    "attacks": "1 blow+spells",
    "damage": "1d4+illusions",
    "morale": "6",
    "treasureType": "",
    "xp": "725",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Polymar",
    "ac": "9",
    "hd": "10*",
    "move": "60'",
    "attacks": "3 blows",
    "damage": "1d6/1d6/1d6",
    "morale": "10",
    "treasureType": "",
    "xp": "1750",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Rakasta",
    "ac": "6",
    "hd": "2+1",
    "move": "90'",
    "attacks": "2 claws/bite",
    "damage": "1d4/1d4/1d4 (war claws)",
    "morale": "9",
    "treasureType": "",
    "xp": "25",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Randara",
    "ac": "0",
    "hd": "14****",
    "move": "180'",
    "attacks": "2 claws/bite",
    "damage": "2d6/2d6/3d6+spells",
    "morale": "9",
    "treasureType": "",
    "xp": "6500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Rock Man",
    "ac": "2",
    "hd": "5**",
    "move": "60'",
    "attacks": "1 fist",
    "damage": "2d6",
    "morale": "9",
    "treasureType": "",
    "xp": "425",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Roper",
    "ac": "0",
    "hd": "12**",
    "move": "30'",
    "attacks": "6 tentacles+bite",
    "damage": "drain STR+5d4",
    "morale": "10",
    "treasureType": "",
    "xp": "3500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Saberclaw",
    "ac": "4",
    "hd": "3+1",
    "move": "150'",
    "attacks": "2 claws/bite",
    "damage": "1d6/1d6/1d8",
    "morale": "9",
    "treasureType": "",
    "xp": "50",
    "monsterType": "Giant Animal (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Scorpion, Normal",
    "ac": "7",
    "hd": "½",
    "move": "150'",
    "attacks": "2 pincers/sting",
    "damage": "1/1/poison",
    "morale": "11",
    "treasureType": "",
    "xp": "6",
    "monsterType": "Normal Animal"
  },
  {
    "source": "Creature Catalog",
    "name": "Sea Serpent",
    "ac": "2",
    "hd": "12**",
    "move": "240'swim",
    "attacks": "1 bite/constrict",
    "damage": "3d8/3d6",
    "morale": "9",
    "treasureType": "",
    "xp": "3500",
    "monsterType": "Monster (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Silver Warrior",
    "ac": "0",
    "hd": "8*",
    "move": "120'",
    "attacks": "2 swords",
    "damage": "1d8/1d8",
    "morale": "12",
    "treasureType": "",
    "xp": "1200",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Sis'thik",
    "ac": "3",
    "hd": "4+1",
    "move": "120'",
    "attacks": "2 claws/bite",
    "damage": "1d6/1d6/2d4",
    "morale": "10",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Sollux (Sun Brother)",
    "ac": "-4",
    "hd": "15***",
    "move": "150'/360'fly",
    "attacks": "2 fists/gaze",
    "damage": "3d6/3d6+blinding",
    "morale": "11",
    "treasureType": "",
    "xp": "5850",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Soul Eater",
    "ac": "-2",
    "hd": "10****",
    "move": "150'",
    "attacks": "1 touch",
    "damage": "2d6+soul drain",
    "morale": "12",
    "treasureType": "",
    "xp": "5000",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Spider, Giant (CC)",
    "ac": "6",
    "hd": "3*",
    "move": "120'",
    "attacks": "1 bite",
    "damage": "2d4+poison",
    "morale": "8",
    "treasureType": "",
    "xp": "50",
    "monsterType": "Giant Animal (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Squid, Giant",
    "ac": "7",
    "hd": "6",
    "move": "120'swim",
    "attacks": "8 tentacles/bite",
    "damage": "1d4 each/1d10",
    "morale": "8",
    "treasureType": "",
    "xp": "275",
    "monsterType": "Giant Animal (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Steam Weevil",
    "ac": "3",
    "hd": "1+1*",
    "move": "90'",
    "attacks": "1 bite",
    "damage": "1d8+steam",
    "morale": "9",
    "treasureType": "",
    "xp": "19",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Strangle Vine",
    "ac": "4",
    "hd": "4*",
    "move": "0",
    "attacks": "1d4+1 vines",
    "damage": "Special (strangle)",
    "morale": "12",
    "treasureType": "",
    "xp": "125",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Thunderhead",
    "ac": "0",
    "hd": "8**",
    "move": "180'fly",
    "attacks": "1 lightning",
    "damage": "4d6",
    "morale": "10",
    "treasureType": "",
    "xp": "1750",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Topi",
    "ac": "7",
    "hd": "1",
    "move": "90'",
    "attacks": "1 weapon",
    "damage": "By weapon",
    "morale": "12",
    "treasureType": "",
    "xp": "10",
    "monsterType": "Undead (Uncommon)"
  },
  {
    "source": "Creature Catalog",
    "name": "Tortle",
    "ac": "3",
    "hd": "4",
    "move": "60'/120'swim",
    "attacks": "1 weapon",
    "damage": "By weapon+2",
    "morale": "9",
    "treasureType": "",
    "xp": "75",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Triton",
    "ac": "4",
    "hd": "4+4",
    "move": "150'swim",
    "attacks": "1 weapon",
    "damage": "By weapon+2",
    "morale": "9",
    "treasureType": "",
    "xp": "200",
    "monsterType": "Humanoid (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Vampire, Nosferatu",
    "ac": "0",
    "hd": "9***",
    "move": "120'/180'fly",
    "attacks": "1 touch+gaze",
    "damage": "1d8+energy drain+charm",
    "morale": "11",
    "treasureType": "",
    "xp": "3100",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Vampire Rose",
    "ac": "7",
    "hd": "4**",
    "move": "0",
    "attacks": "1d4 tendrils",
    "damage": "1d4 each+blood drain",
    "morale": "12",
    "treasureType": "",
    "xp": "175",
    "monsterType": "Lowlife (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Velya",
    "ac": "2",
    "hd": "7**",
    "move": "120'swim",
    "attacks": "1 touch",
    "damage": "1d8+charm+energy drain",
    "morale": "11",
    "treasureType": "",
    "xp": "1250",
    "monsterType": "Undead (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Water Weird",
    "ac": "0",
    "hd": "6**",
    "move": "60' (aquatic)",
    "attacks": "1 grapple",
    "damage": "Drown",
    "morale": "12",
    "treasureType": "",
    "xp": "725",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "White-Fang",
    "ac": "6",
    "hd": "2+2",
    "move": "120'/180'swim",
    "attacks": "1 bite",
    "damage": "1d8+cold",
    "morale": "8",
    "treasureType": "",
    "xp": "25",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Winged Warrior",
    "ac": "2",
    "hd": "6",
    "move": "120'/240'fly",
    "attacks": "2 weapons",
    "damage": "By weapon×2",
    "morale": "10",
    "treasureType": "",
    "xp": "275",
    "monsterType": "Monster (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Wood Imp",
    "ac": "4",
    "hd": "1**",
    "move": "60'/120'fly",
    "attacks": "1 spell/weapon",
    "damage": "Special",
    "morale": "6",
    "treasureType": "",
    "xp": "19",
    "monsterType": "Enchanted (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Wychglow",
    "ac": "6",
    "hd": "4**",
    "move": "120'fly",
    "attacks": "1 touch",
    "damage": "1d8+confusion",
    "morale": "10",
    "treasureType": "",
    "xp": "175",
    "monsterType": "Enchanted (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Wychlamp",
    "ac": "4",
    "hd": "6**",
    "move": "120'fly",
    "attacks": "1 touch",
    "damage": "2d6+charm",
    "morale": "10",
    "treasureType": "",
    "xp": "725",
    "monsterType": "Enchanted (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Wyrd",
    "ac": "3",
    "hd": "3**",
    "move": "90'/150'fly",
    "attacks": "1 weapon+curse",
    "damage": "By weapon+special",
    "morale": "8",
    "treasureType": "",
    "xp": "65",
    "monsterType": "Undead (Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Xytar",
    "ac": "-2",
    "hd": "16****",
    "move": "150'",
    "attacks": "2 claws/bite+spell",
    "damage": "2d8/2d8/3d10+magic",
    "morale": "11",
    "treasureType": "",
    "xp": "7500",
    "monsterType": "Planar (V.Rare)"
  },
  {
    "source": "Creature Catalog",
    "name": "Yowler",
    "ac": "5",
    "hd": "3+1**",
    "move": "150'",
    "attacks": "2 claws/bite",
    "damage": "1d6/1d6/1d8+howl",
    "morale": "9",
    "treasureType": "",
    "xp": "100",
    "monsterType": "Monster (Rare)"
  }
];
})();
